services:
  v2-sub-page:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: v2-sub-page
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
