services:
  v2-sub-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v2-sub-page
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000"
    volumes:
      - /root/dev/Market/ech-updater-data:/app/ech-updater-data:ro
